### ISSUE TITLE
TTS(TCP) でエラー

### ISSUE THREAD

**Issue by alalwww** [anoyetta/ACT.TTSYukkuri#10]
以下のようなエラーが頻発するので報告します。
```
2017-11-19 03:44:03.9869 [Error] 棒読みちゃんの読上げで例外が発生しました。 System.ArgumentException: ストリームに書き込めませんでした。
   場所 System.IO.BinaryWriter..ctor(Stream output, Encoding encoding, Boolean leaveOpen)
   場所 ACT.TTSYukkuri.Boyomichan.BoyomichanSpeechController.Speak(String text)
```
```
2017-11-19 03:47:32.9408 [Error] 棒読みちゃんの読上げで例外が発生しました。 System.ObjectDisposedException: 破棄されたオブジェクトにアクセスできません。
オブジェクト名 'System.Net.Sockets.NetworkStream' です。
   場所 System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   場所 ACT.TTSYukkuri.Boyomichan.BoyomichanSpeechController.Speak(String text)
```

## 症状
狙って再現できないので、確実に確認できたわけではないですが、エラー発生時は読み上げがされてないと思います。また、エラー発生と同タイミングかの確認はできていませんが、エラーが発生する戦闘中などログ量が増えてる状態で、読み上げの音声がデフォルトに変わる、音量が変わる、読み上げ速度が非常に低速になる、などが同時に発生することもあります。
また、棒読みちゃん側にエラーが出ることもあります。
(エラー内容を記録し忘れてたのでログ取れたら追記します。幾つかありましたが、文字コード関連のエラーなどあまり関連してなさそうな内容だったので、通信が途中できれてデータ破損したとかかも？)

## 発生時期
きちんと記録してないので記憶違いでなければですが、Discord統合が入ったか、UI変更がされたあたりから発生するようになったよう記憶しています。

## 再現性
確実な再現手順はないですが、ログ量の多いコンテンツほど発生頻度は上がるように思えます。
ソロではほぼ見ませんが、4人ID、8人レイド、モブハン、24レイドなど、高頻度でログが流れるコンテンツになるほど多発します。テストボタンの連打では今のところ再現してません。

## 環境
Win10Pro、DX11、棒読みちゃん Ver0.1.11.0 Beta 16
FFXIV_ACT_Plugin v1.6.1.8、ACT.Hojoring v4.0.9、ACT.TTSYukkuri v3.3.0

TTS.Yukkuri -> TCP -> 棒読みちゃんの環境です。
再生方式はWASAPIで、サブ再生デバイスは無効。

CustomTriggersは40程度、スペスペのSpells/Tickersはおよそ60程度あり、全てではないですが多くをTTSに流してます。

スタックトレースだけ見ると、GCされてしまったオブジェクトやGCされたことで閉じられてしまったストリームにアクセスして発生してそう？非同期処理に起因する問題とか、かも？

**Comment by alalwww** [comment]
書いてから気づいた。Issueも補助輪にまとめたほうがいいのかな？
必要であれば転記するのでいってください。

**Comment by anoyetta** [comment]
補助輪のほうに移動させておいてください。
