### ISSUE TITLE
Discord bot channel joining not working

### ISSUE THREAD

**Issue by Ziazis** [anoyetta/ACT.TTSYukkuri#6]
I'm not really sure if that is a configuration error on my side or if there is an error in the plugin.

As soon as I click on the join channel button I get an error and ACT crashes.
The bot does join the discord server though. 

Maybe you can help me figure the log message out?

.NET Runtime error:

> Anwendung: Advanced Combat Tracker.exe Frameworkversion: v4.0.30319  Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.  Ausnahmeinformationen: System.DllNotFoundException bei  DSharpPlus.VoiceNext.Codec.OpusCodec.CreateEncoder(Int32, Int32, Int32,  DSharpPlus.VoiceNext.Codec.OpusError ByRef) bei  DSharpPlus.VoiceNext.Codec.OpusCodec..ctor(Int32, Int32,  DSharpPlus.VoiceNext.Codec.VoiceApplication) bei  DSharpPlus.VoiceNext.VoiceNextConnection..ctor(DSharpPlus.DiscordClient,  DSharpPlus.Entities.DiscordGuild, DSharpPlus.Entities.DiscordChannel,  DSharpPlus.VoiceNext.VoiceNextConfiguration,  DSharpPlus.VoiceNext.VoiceEntities.VoiceServerUpdatePayload,  DSharpPlus.VoiceNext.VoiceEntities.VoiceStateUpdatePayload) bei  DSharpPlus.VoiceNext.VoiceNextClient+<ConnectAsync>d__21.MoveNext()  Ausnahmeinformationen: System.AggregateException bei  System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0,  Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResultCore(Boolean) bei  ACT.TTSYukkuri.Discord.Models.DiscordClientModel+<>c__DisplayClass34_0.<Join>b__0(System.Threading.Tasks.Task`1<DSharpPlus.VoiceNext.VoiceNextConnection>)  bei  System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[[System.__Canon,  mscorlib, Version=4.0.0.0, Culture=neutral,  PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0,  Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke() bei  System.Threading.Tasks.Task.Execute() bei  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bei  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)  bei  ACT.TTSYukkuri.Discord.Models.DiscordClientModel+<Join>d__34.MoveNext()  bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bei  System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,  System.Object, Int32) bei  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,  System.Delegate, System.Object, Int32, System.Delegate) bei  System.Windows.Threading.DispatcherOperation.InvokeImpl() bei  System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) bei  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object, Boolean) bei  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,  System.Threading.ContextCallback, System.Object) bei  MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext,  System.Threading.ContextCallback, System.Object) bei  System.Windows.Threading.DispatcherOperation.Invoke() bei  System.Windows.Threading.Dispatcher.ProcessQueue() bei  System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr,  Boolean ByRef) bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr,  Boolean ByRef) bei  MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) bei  System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,  System.Object, Int32) bei  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object,  System.Delegate, System.Object, Int32, System.Delegate) bei  System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority,  System.TimeSpan, System.Delegate, System.Object, Int32) bei  MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) bei  System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef) bei  System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr,  Int32, Int32) bei  System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32,  System.Windows.Forms.ApplicationContext) bei  System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32,  System.Windows.Forms.ApplicationContext) bei  Advanced_Combat_Tracker.ActLoader.Main(System.String[])

**Comment by anoyetta** [comment]
You must install in the same directory as "Advanced Combat Tracker.exe"
libopus.dll
libsodium.dll

**Comment by Ziazis** [comment]
Ah, that was it thanks.
