### ISSUE TITLE
指定されたモジュールが見つかりません。

### ISSUE THREAD

**Issue by NumLockMana** [anoyetta/ACT.TTSYukkuri#9]
Issuesへの投稿は初めてです。
HojoringをダウンロードしてYukkuriを更新したらエラーが発生しました。
一旦ACTを終了し、Actorを利用して入れ直すと正常に動きました。

エラー発生時のログ

>  [TRACE] ACT.TTSYukkuri.PluginCore.InitPlugin() ACT.TTSYukkuri.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null start. 
>  [TRACE] FFXIV.Framework.Common.UpdateChecker.ShowSplash() *** FFXIV_ACT_Plugin v1.6.1.8 *** 
>  [TRACE] FFXIV.Framework.Common.UpdateChecker.ShowSplash() *** Hojoring v4.0.9 *** 
>  [TRACE] ACT.TTSYukkuri.KanjiTranslator.Initialize() IFELANG Connected. 
>  [ERROR] ACT.TTSYukkuri.PluginCore.InitPlugin() InitPlugin error. System.IO.FileNotFoundException: 指定されたモジュールが見つかりません。 (HRESULT からの例外:0x8007007E)
>    場所 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
>    場所 ACT.TTSYukkuri.Yukkuri.AquesTalk.Load()
>    場所 ACT.TTSYukkuri.Yukkuri.YukkuriSpeechController.Initialize()
>    場所 ACT.TTSYukkuri.SpeechController.get_Default()
>    場所 ACT.TTSYukkuri.PluginCore.InitPlugin(IActPluginV1 plugin, TabPage pluginScreenSpace, Label pluginStatusText)
>  [ERROR] ACT.TTSYukkuri.PluginCore.DeInitPlugin() DeInitPlugin error. System.IO.FileNotFoundException: 指定されたモジュールが見つかりません。 (HRESULT からの例外:0x8007007E)
>    場所 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
>    場所 ACT.TTSYukkuri.Yukkuri.AquesTalk.Load()
>    場所 ACT.TTSYukkuri.Yukkuri.YukkuriSpeechController.Initialize()
>    場所 ACT.TTSYukkuri.SpeechController.get_Default()
>    場所 ACT.TTSYukkuri.PluginCore.DeInitPlugin()
 
 正常に起動したときのログ。
>  [TRACE] ACT.TTSYukkuri.PluginCore.InitPlugin() ACT.TTSYukkuri.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null start. 
>  [TRACE] FFXIV.Framework.Common.UpdateChecker.ShowSplash() *** FFXIV_ACT_Plugin v1.6.1.8 *** 
>  [TRACE] FFXIV.Framework.Common.UpdateChecker.ShowSplash() *** Hojoring v4.0.9 *** 
>  [TRACE] ACT.TTSYukkuri.PluginCore.InitPlugin() ACT.TTSYukkuri.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null start. 
>  [TRACE] FFXIV.Framework.Common.UpdateChecker.ShowSplash() *** FFXIV_ACT_Plugin v1.6.1.8 *** 
>  [TRACE] FFXIV.Framework.Common.UpdateChecker.ShowSplash() *** Hojoring v4.0.9 *** 
>  [TRACE] ACT.TTSYukkuri.KanjiTranslator.Initialize() IFELANG Connected. 

Actorを利用すると、Yukkuriフォルダ内へ
AquesTalk.dll/AquesTalkDriver.dll/AqKanji2Koe.dllが生成されてまして、
これらが無い場合にエラーが発生するようです。

![2017111701](https://user-images.githubusercontent.com/33511727/32934614-ac085834-cbaf-11e7-9d68-4afcef3aab22.jpg)

必要か分かりませんがFFXIV.Framework.TTS.Server.logは以下の通り。

>  [TRACE] FFXIV.Framework.TTS.Server.App.App_Startup() begin. 
>  [INFO ] FFXIV.Framework.TTS.Server.App.App_Startup() FFXIV.Framework.TTS.Server v1.1.3 
>  [INFO ] FFXIV.Framework.TTS.Server.RemoteTTSServer.Open() IPC Channel Listened. Uri=ipc://FFXIV.Framework.TTS.Server/TTSModel 
>  [TRACE] FFXIV.Framework.TTS.Server.App.App_Startup() end. 
> 

Windows10　64bit
NET Framework　4.7.02046

**Comment by anoyetta** [comment]
解消しているので何のissueなのか分かりませんが...。

エラーになったときはdllの配置が正しくありません。所定の位置にdllがないため、見つからない→ロードできないというエラーです。
手動で配置したときに配置を間違えている。漏れているのが原因です。

**Comment by NumLockMana** [comment]
当方の解凍ソフトが正常に作動していなかった事が原因でした。
お騒がせしました。
